// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zciaplmrcqlxxprgasqf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpjaWFwbG1yY3FseHhwcmdhc3FmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMTgwMDcsImV4cCI6MjA3MTc5NDAwN30.OJsfvXSsrdmxkzogMVcCoR-e2jXZg47ZvXYsvrN_P-o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});