// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jhyikzxnzlemrtykbndd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpoeWlrenhuemxlbXJ0eWtibmRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3OTA5OTMsImV4cCI6MjA2OTM2Njk5M30.ez--4RS0MaO4nlo6RzCzPQduU0DIM4QxFbLoQNukZm4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});